AutoDealership/Models/Vehicle.cs
using AutoDealership.Models.Types;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoDealership.Models
{
    public class Vehicle
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Brand")]
        public int BrandId { get; set; }
        public string Model { get; set; }
        [Display(Name = "Fuel Type")]
        public Fuel FuelType { get; set; }
        public string Features { get; set; }
        [Display(Name = "Body Style")]
        public BodyStyle BodyStyle { get; set; }
        public Transmission Transmission { get; set; }
        public int Year { get; set; }

        //Mileage is stored in kilometers
        public int Mileage { get; set; }
        [Display(Name = "Drivetrain")]
        public Drivetrain DrivetrainType { get; set; }
        [Display(Name = "Exterior Color")]
        public string Color { get; set; }
        [Display(Name = "Interior Color")]
        public string InteriorColor { get; set; }

        //Fuel efficiency is stored in l/100km
        [Display(Name = "Fuel Efficiency")]
        public double FuelEfficiency { get; set; }
        [Display(Name = "Power")]
        public int Horsepower { get; set; }
        public int Torque { get; set; }
        public string Engine { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public bool IsForLease { get; set; }
        public bool IsForRent { get; set; }

        //If vehicle is for lease
        public int MonthlyPayment { get; set; }
        //If vehicle is for rent
        public int DailyPayment { get; set; }
        [Display (Name = "Vehicle Status")]
        public VehicleStatus VehicleStatus { get; set; }
        public bool InStock { get; set; }
        public bool IsTestDriven { get; set; }
        [Display(Name = "Vehicle Image")]
        public string CoverImageURL { get; set; }
        public string ImagesURL { get; set; }


        public double GetMPG()
        {
            return 235.214583 / FuelEfficiency;
        }  
    }
}

AutoDealership/Models/VehicleViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AutoDealership.Models
{
    public class CreateVehicleViewModel
    {
        public Vehicle Vehicle { get; set; }
        public IEnumerable<Brand> Brands { get; set; }
        public Brand NewBrand { get; set; }
        public string ListOfFeatures { get; set; }
        public string ListOfImages { get; set; }
    }

    public class VehicleDetailsViewModel
    {
        public Vehicle Vehicle { get; set; }
        public Brand Brand { get; set; }
    }

    public class MyReservationViewModel
    {
        public ApplicationUser User { get; set; }
        public List<Vehicle> TestDriveVehicles { get; set; }
        public Vehicle ReservedVehicle { get; set; }
        public VehicleReservation ReservationDetails { get; set; }
        public List<VehicleReservation> TestDrivesDetails { get; set; }
    }

    public class InventoryViewModel
    {
        public List<Vehicle> Inventory { get; set; }
        public List<Vehicle> FullInventory { get; set; }
        public string[] SearchQuery { get; set; }
        public List<Brand> AllBrands { get; set; }
        public int NumCols { get; set; }
        public string SortOrder { get; set; }
        public int Pages { get; set; }
        public int ActivePage { get; set; }
    }

}

AutoDealership/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoDealership.Models;

namespace AutoDealership.Controllers
{
    public class VehicleController : Controller
    {
        private ApplicationDbContext db;

        public VehicleController(ApplicationDbContext db)
        {
            this.db = db;
        }

        // GET: Vehicle
        [Authorize(Roles = "Editor, Administrator")]
        public ActionResult Index()
        {
            ViewBag.Brands = db.Brands.Include(b => b.Vehicles).ToList();
            return View(db.Vehicles.ToList());
        }

        // GET: Vehicle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            //Vehicle vehicle = db.Vehicles.Include(v => v.ImagesURL).Where(v => v.Id == id).FirstOrDefault();
            Brand brand = db.Brands.Find(vehicle.BrandId);
            VehicleDetailsViewModel model = new VehicleDetailsViewModel();
            model.Vehicle = vehicle;
            model.Brand = brand;
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            if(User != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    ApplicationUser user = db.Users.Include("ViewedVehicles").FirstOrDefault(u => u.Email.Equals(User.Identity.Name));
                    if (user.ViewedVehicles == null) user.ViewedVehicles = new List<Vehicle>();
                    if (user.ViewedVehicles.Count >= 4)
                    {
                        user.ViewedVehicles = user.ViewedVehicles.Reverse().Take(3).Reverse().ToList();
                    }
                    user.ViewedVehicles.Add(vehicle);
                    db.SaveChanges();
                    ViewData["CurrentUser"] = user;
                    ViewData["Brands"] = db.Brands.ToList();
                }
            }
            return View(model);
        }
        [Authorize(Roles = "Editor, Administrator")]
        // GET: Vehicle/Create
        public ActionResult Create()
        {
            CreateVehicleViewModel model = new CreateVehicleViewModel();
            model.Brands = db.Brands.ToList();
            return View(model);
        }

        [Authorize(Roles = "Editor, Administrator")]
        // POST: Vehicle/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BrandId,Model,FuelType,BodyStyle,Features,ImagesURL,Transmission,Year,Mileage,DrivetrainType,Color,InteriorColor,FuelEfficiency,Horsepower,Torque,Engine,Description,Price,IsForLease,IsForRent,MonthlyPayment,DailyPayment,VehicleStatus,InStock,CoverImageURL")] Vehicle vehicle)
        {
            //string[] featureArray = viewModel.ListOfFeatures.Split(new string[] { "\r\n" }, StringSplitOptions.None);
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                //var brand = db.Brands.Include(b => b.Vehicles).Where(b => b.Name.Equals(vehicle.Brand.Name)).FirstOrDefault();
                var brand = db.Brands.Include(b => b.Vehicles).Where(b => b.Id.Equals(vehicle.BrandId)).FirstOrDefault();
                if(brand != null)
                {
                    //vehicle.Brand = brand;
                    if(brand.Vehicles == null)
                    {
                        brand.Vehicles = new List<Vehicle>();
                    }
                    brand.Vehicles.Add(vehicle);
                    //db.Entry<Vehicle>(vehicle).State = EntityState.Modified;
                    //db.Entry<Brand>(brand).State = EntityState.Modified;
                    db.Vehicles.Add(vehicle);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            CreateVehicleViewModel model = new CreateVehicleViewModel();
            model.Vehicle = vehicle;
            model.Brands = db.Brands.ToList();
            return View(model);
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult CreateBrand()
        {
            CreateVehicleViewModel model = new CreateVehicleViewModel();
            model.Brands = db.Brands.ToList();
            return View("CreateBrand", model);
        }
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult CreateBrand(CreateVehicleViewModel model)
        {
            model.NewBrand.Vehicles = new List<Vehicle>();
            db.Brands.Add(model.NewBrand);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        public ActionResult GetBrand(int id)
        {

            var brand = db.Brands.Find(id);
            if (brand != null)
                return Json(brand, JsonRequestBehavior.AllowGet);
            return HttpNotFound();
            
        }
        [Authorize(Roles = "Administrator")]
        public ActionResult Brands() 
        {
            return View(db.Brands.Include(b => b.Vehicles).ToList());
        }

        // GET: Vehicle/EditBrand/5
        [Authorize(Roles = "Administrator")]
        public ActionResult EditBrand(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Include(b => b.Vehicles).Where(b => b.Id == id).FirstOrDefault();
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        //POST: Vehicle/EditBrand/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBrand([Bind(Include = "Id,Name,LogoURL,Vehicles")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Brands");
        }

        // GET: Vehicle/Edit/5
        [Authorize(Roles = "Administrator, Editor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            ViewData["Brands"] = db.Brands.ToList();
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicle/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BrandId,Model,FuelType,Features,ImagesURL,BodyStyle,Transmission,Year,Mileage,DrivetrainType,Color,InteriorColor,FuelEfficiency,Horsepower,Torque,Engine,Description,Price,IsForLease,IsForRent,MonthlyPayment,DailyPayment,VehicleStatus,InStock,CoverImageURL")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: Vehicle/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // DELETE: Vehicle/DeleteAllFromBrand
        [HttpDelete]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteAllFromBrand(int id)
        {
            var brand = db.Brands.Include(b => b.Vehicles).Where(b => b.Id == id).FirstOrDefault();
            var vehiclesInBrand = brand.Vehicles;
            foreach(var vehicle in vehiclesInBrand.ToList())
            {
                db.Vehicles.Remove(vehicle);
            }
            brand.Vehicles.Clear();
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VehicleReservations()
        {
            ViewBag.Users = db.Users.ToList();
            ViewBag.Vehicles = db.Vehicles.ToList();
            return View(db.VehicleReservations.ToList());
        }
        [Authorize]
        [HttpPost]
        public ActionResult ReserveVehicle(VehicleReservation model)
        {
            var user = db.Users.Where(u => u.UserName.Equals(model.UserId)).FirstOrDefault();
            model.UserId = user.Id;
            var vehicle = db.Vehicles.Find(model.VehicleId);
            if (model.IsTestDrive) 
            { 
                vehicle.IsTestDriven = true;
            }
            else
            {
                user.ReservedVehicleId = vehicle.Id;

AutoDealership/Controllers/api/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoDealership.Models;

namespace AutoDealership.Controllers
{
    public class VehiclesController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: api/Vehicles
        public IQueryable<Vehicle> GetVehicles()
        {
            return db.Vehicles;
        }

        // GET: api/Vehicles/5
        [ResponseType(typeof(Vehicle))]
        public IHttpActionResult GetVehicle(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return Ok(vehicle);
        }

        // PUT: api/Vehicles/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutVehicle(int id, Vehicle vehicle)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vehicle.Id)
            {
                return BadRequest();
            }

            db.Entry(vehicle).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!VehicleExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Vehicles
        [ResponseType(typeof(Vehicle))]
        public IHttpActionResult PostVehicle(Vehicle vehicle)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Vehicles.Add(vehicle);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = vehicle.Id }, vehicle);
        }

        // DELETE: api/Vehicles/5
        [ResponseType(typeof(Vehicle))]
        public IHttpActionResult DeleteVehicle(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return NotFound();
            }

            db.Vehicles.Remove(vehicle);
            db.SaveChanges();

            return Ok(vehicle);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool VehicleExists(int id)
        {
            return db.Vehicles.Count(e => e.Id == id) > 0;
        }
    }
}

AutoDealership/Views/Shared/_ManageDashboardPanel.cshtml
@model AutoDealership.Models.IndexViewModel

<div class="container">
    <h4>Dashboard</h4>
    <hr />
    @if (User.IsInRole("Administrator"))
    {
        <div class="row">
            <div class="col">
                <div>
                    @Html.ActionLink("List of users", "AllUsers", "Account", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
                    @*<button class="btn btn-block btn-outline-dark">List of users</button>*@
                </div>
            </div>

            <div class="col">
                <div>
                    @Html.ActionLink("List of Vehicles","Index","Vehicle", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
                    @*<button class="btn btn-block btn-outline-info">List of Vehicles</button>*@
                </div>
            </div>

            <div class="col">
                <div>
                    @Html.ActionLink("List of Reservations / Test Drives", "VehicleReservations", "Vehicle", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
                    @*<button class="btn btn-block btn-outline-info">List of Reservations / Test Drives</button>*@
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col">
                <div>
                    @Html.ActionLink("List of roles","Roles","Account", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
                </div>
            </div>

            <div class="col">
                <div>
                    @Html.ActionLink("List a new vehicle", "Create", "Vehicle", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
                </div>
            </div>

            <div class="col">
                <div>
                    @Html.ActionLink("List of brands", "Brands", "Vehicle", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
                </div>
            </div>
        </div>
    }
    @if (User.Identity.IsAuthenticated) 
    { 
<div class="row">
    <div class="col">
        @Html.ActionLink("My reservations", "MyReservations", "Vehicle", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
    </div>
    <div class="col">
        @Html.ActionLink("Last viewed listings", "MyViewedVehicles", "Vehicle", new { area = "" }, new { @class = "my-blue-background-color text-white btn-lg btn p-5 rounded-1 m-3 dashboard-panel" })
    </div>
</div>
    }
</div>

AutoDealership/Views/Shared/_ManageUserPanel.cshtml
@model AutoDealership.Models.IndexViewModel


<div class="container">
    <h4>Profile Information</h4>
    <hr />
    <div class="container mb-3">
        <div class="row">
            <h3>Hello <b>@Model.User.FullName!</b></h3>
        </div>
        <div class="row">
            <h6 class="text-muted">Here you can view and edit your profile information</h6>
        </div>
    </div>

    <hr />

    <div class="row mb-4">
        <div class="col">
            <strong style="font-size: 1.5em" class="pb-sm-1 border-bottom border-warning border-3">Email</strong>
            <br />
            <p class="fs-6 fw-normal mt-sm-3">@Model.User.Email</p>
            <button class="btn btn-warning shadow">Change your email</button>
        </div>

        <div class="col">
            <strong style="font-size: 1.5em" class="pb-sm-1 border-bottom border-warning border-3">Phone Number</strong>
            <br />
            <div>
                <p class="fs-6 fw-normal mt-sm-3">@(Model.PhoneNumber ?? "None")</p>
                @if (Model.PhoneNumber != null)
                {
                    <br />
                    <text>[&nbsp;&nbsp;@Html.ActionLink("Change", "AddPhoneNumber")&nbsp;&nbsp;]</text>
                    using (Html.BeginForm("RemovePhoneNumber", "Manage", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <text>[<input type="submit" value="Remove" class="btn-link" />]</text>
                    }
                }
                else
                {
                    <text>@Html.ActionLink("Add a phone number", "AddPhoneNumber", null, new { @class = "btn btn-warning shadow" })</text>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            @*to fix enabling/disabling two factor*@
            <strong style="font-size: 1.5em" class="pb-sm-1 border-bottom border-warning border-3">Two Factor Authentication</strong>
            @if (!Model.User.TwoFactorEnabled)
            {
                <p class="fs-6 fw-normal text-danger mt-sm-3">Two Factor Authentication is not enabled</p>
                @Ajax.ActionLink("Enable Two Factor Authentication", "EnableTwoFactorAuthentication", "Manage",null, new AjaxOptions { HttpMethod = "Post" }, new { @class = "btn btn-warning shadow" })
                @*@Html.ActionLink("Enable Two Factor Authentication", "EnableTwoFactorAuthentication", "Manage", null, new { @class = "btn btn-warning shadow" })*@
            }
        </div>
        <div class="col">
            <strong style="font-size: 1.5em" class="pb-sm-1 border-bottom border-warning border-3">Password</strong>
            @if (!Model.HasPassword)
            {
                <p class="fs-6 fw-normal text-danger mt-sm-3">WARNING! You haven't set a password, it is highly recommended to set a password to guarantee your account is protected!</p>
                @Html.ActionLink("Set a password", "SetPassword", "Manage", null, new { @class = "btn btn-warning shadow" })
            }
            else
            {
                <p class="fs-6 fw-normal mt-sm-3">Your account is protected by a strong password (minimum 1 lowercase and 1 uppercase letter, 1 number and a special character)</p>
                @Html.ActionLink("Change your password", "ChangePassword", "Manage", null, new { @class = "btn btn-warning shadow" })
            }
        </div>
    </div>

</div>

AutoDealership/Views/Shared/_PageHeader.cshtml
<div class="row mb-5">
        @if (ViewData["ActiveNav"].ToString().ToLower().Contains("speed"))
        {
        <div class="text-center" id="contact-header" style="background-image: url(https://www.greatamericandays.com/sites/default/files/styles/product_page_main_image/public/product_images/Supercars-Page-Header.jpg?itok=O61ZJeX9)">
        }

            <div class="p-5">
                <h2 class="h2 text-white fw-bold">@ViewData["ActiveNav"]</h2>
                <h5 class="h5 text-white">Home > @ViewData["ActiveNav"]</h5>
            </div>
        </div>
</div>

AutoDealership/Views/Shared/_ReserveVehicle.cshtml
@model AutoDealership.Models.VehicleReservation
@using AutoDealership.Models
@{ 
    var db = new ApplicationDbContext();
    var vehicle = db.Vehicles.Find(Model.VehicleId);
    var brand = db.Brands.Find(vehicle.BrandId);
} 

@using (Html.BeginForm("ReserveVehicle", "Vehicle"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @if (!Model.IsTestDrive)
    {
        @*<h4>Vehicle Reservation Form</h4>*@
        <h6>You are about to reserve this vehicle for purchase. The reservation will be made using the information that you have in your account.</h6>
    }
    else
    {
        <h6>Experience what it's like behind the wheel of this @vehicle.Year @brand.Name @vehicle.Model and get all your questions answered</h6>
    }
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@
    @Html.HiddenFor(model => model.UserId)

    @*<div class="form-group">
            @Html.LabelFor(model => model.VehicleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @Html.HiddenFor(model => model.VehicleId)

    @Html.HiddenFor(model => model.IsTestDrive)

    @*<div class="form-group">
            @Html.LabelFor(model => model.IsTestDrive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsTestDrive)
                    @Html.ValidationMessageFor(model => model.IsTestDrive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

<div class="form-group">
    @if (!Model.IsTestDrive)
    {
        <h6 class="pb-2">Please select the date and time which you would like to make your appointment by:</h6>
    }
    else
    {
        <h6 class="pb-2">Please select the date and time when you would like to test drive this vehicle. All test drives last for 1 hour.</h6>
    }
    @*@Html.LabelFor(model => model.ReservedUntil, htmlAttributes: new { @class = "control-label col-md-2" })*@
    <div class="col-md-10">
        @Html.EditorFor(model => model.ReservedUntil, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
        @Html.ValidationMessageFor(model => model.ReservedUntil, "", new { @class = "text-danger" })
    </div>
</div>

    @*<div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1" />
                            <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>*@


<div class="form-group">
    <div class="mt-5 m-auto">
        @if (!Model.IsTestDrive)
        {
            <input id="confirm-reservation-btn" type="submit" value="Confirm reservation" class="text-center btn btn-warning text-primary fw-semibold" />
        }
        else
        {
            <input id="confirm-test-drive-btn" type="submit" value="Schedule test drive" class="text-center btn btn-warning text-primary fw-semibold" />
        }
    </div>
</div>
</div>
}

AutoDealership/Views/Shared/_RoleToUser.cshtml
@model AutoDealership.Models.UserRoleViewModel

@using (Html.BeginForm("SetRoleToUser", "Account"))
{
    @Html.HiddenFor(model => model.UserEmail)
    @Html.HiddenFor(model => model.Roles)
    <h5 class="h5 mb-3">Change Role for User: <strong>@Model.UserEmail</strong></h5>

    <h6 class="h6 mb-5">Current Role: <span class="badge bg-dark">@Model.CurrentRole</span></h6>

    @*<h6 class="display-6"><strong>User: </strong> @Model.UserEmail</h6>*@

    @Html.DropDownListFor(model => model.SelectedRole, new SelectList(Model.Roles), new { @class="form-select w-50 d-inline me-3" })

    <button type="submit" class="btn btn-dark">Save Changes</button>

}